bluewave-labs/verifywise

- Clients/src/presentation/components/Modals/Controlpane/index.tsx
Small fix of background color related to issue #167
> Background color fix

- Clients/src/presentation/components/Modals/ComplianceFeedback/ComplianceFeedback.tsx
- Clients/src/presentation/mocks/compliance.data.ts
> Wording Fixes on Compliance tracker

- Clients/src/presentation/components/CreateProjectForm/index.tsx
> Changed users field to select

- Clients/src/presentation/mocks/projects/project-vendor-risks.data.ts
- Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
> 015 nov 05 modify vendor risks table

- Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
> Implemented pagination in Project risks & Vendor risks tables

- Servers/validations/email.valid.ts
- Servers/validations/number.valid.ts
- Servers/validations/password.valid.ts
Addressing to 
close #115 
close #116
> Table content validation

- Clients/src/presentation/mocks/projects/project-risks.data.ts
- Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
> Removed "Probability" from Project risks table

- Clients/.env
- Clients/env.vars.ts
- Clients/index.html
- Clients/package.json
- Clients/src/application/repository/entity.repository.ts
- Clients/src/infrastructure/api/customAxios.ts
- Clients/src/infrastructure/api/networkServices.ts
- Clients/src/presentation/components/RichTextEditor/index.tsx
- Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
- Clients/src/presentation/pages/Assessment/NewAssessment/assessments.tsx
- Clients/src/presentation/pages/Assessment/NewAssessment/priorities.tsx
- Clients/vite.config.ts
- Servers/index.ts
- Servers/package-lock.json
- Servers/package.json
> 038 nov 19 getting input values assessment tracker

- Clients/src/presentation/components/CreateProjectForm/index.tsx
- Clients/src/presentation/components/Modals/Controlpane/index.tsx
- Clients/src/presentation/components/Modals/NewVendor/index.tsx
- Clients/src/presentation/components/Popup/index.tsx
- Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
- Clients/src/presentation/pages/Assessment/index.tsx
- Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
- Clients/src/presentation/pages/SettingsPage/Password/index.tsx
- Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
- Clients/src/presentation/pages/Vendors/index.tsx
- Clients/src/presentation/themes/v1SingleTheme.ts
> background color for hover effect is restored

- Clients/src/App.tsx
- Clients/src/application/authentication/authSlice.ts
- Clients/src/application/repository/entity.repository.ts
- Clients/src/presentation/components/ProtectedRoute/index.tsx
- Clients/src/presentation/components/Sidebar/index.tsx
- Servers/controllers/user.ctrl.ts
- Servers/endpoints-test/user.http.test.rest
- Servers/mocks/tools/user.mock.db.ts
- Servers/routes/user.route.ts
- Servers/utils/user.utils.ts
Addressing to the issue #148 . close #148 
Also followings:
the issue #65 . close #65 
And the issue #2 . close #2 
@gorkemcetin 
I'm closing all the above issues, since they're whether done or deprecated and what's left from some of them is after V1.0; therefore, I'll create new issues/milestones for what's let left.
> 044 dec 2 authentication pages

- Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
- Clients/src/presentation/components/Inputs/Select/index.tsx
- Clients/src/presentation/components/Modals/ComplianceFeedback/ComplianceFeedback.tsx
- Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
- Clients/src/presentation/components/RichTextEditor/index.tsx
> Capturing values for controls

- Clients/src/presentation/components/Inputs/Field/index.css
addressing to close issue #341
Here's how it looks now @gorkem-bwl :
> 050 dec 13 overflow in compliance tracker

- Clients/src/presentation/components/CreateProjectForm/index.tsx
@samuel-coutinho , I just completed the issue that was assigned to you for modals. please make sure you sync your repo
The Screen shot:
> Confirmation modal for Create new project added

- Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
@melpsh , this issue was assigned to you, but to boost things up its done now. Please make sure you sync your repository.
Close issue #345
> Confirmation modal added for the compliance tracker

- Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
- Servers/controllers/user.ctrl.ts
- Servers/mocks/users.data.ts
- Servers/models/user.model.ts
- Servers/utils/user.utils.ts
@salmanja and @melpsh , the data now loads into Fields.
@salmanja , you weren't extracting the values from the response
@melpsh some of the alignments and font issues are fixed now.
@gorkemcetin the new modal is now replaced.
1- ![Screenshot 2024-12-16 123405](https://github.com/user-attachments/assets/3f6b0019-e3f0-4ac5-83a1-0e532c695e5e)
2 - ![Screenshot 2024-12-16 123419](https://github.com/user-attachments/assets/90308ba2-5194-4e4f-a9b7-e91dd43cf6e6)
3 - ![Screenshot 2024-12-16 123428](https://github.com/user-attachments/assets/4bfcd90a-b9d9-482a-982a-85deaeee0da1)
> 053 dec 16 settings page polishing

- Clients/src/presentation/pages/SettingsPage/Password/index.tsx
Spacings, Alignments are fixed in the Password tab.
Also New Modal is replaced
Addressing to close #312
> Enhancements on Settings/password tab

- Clients/src/presentation/components/Sidebar/index.tsx
- Clients/src/presentation/containers/Dashboard/index.tsx
- Clients/src/presentation/pages/ProjectView/Overview/index.tsx
@gorkem-bwl 
Now, the sidebar select gets the data from the backend.
@samuel-coutinho 
To help you push things forward a bit, I'm getting projects and users from the backend inside Project View/Overview (tab)
> 055 dec 16 connecting to be

- Clients/src/application/repository/entity.repository.ts
- Clients/src/presentation/pages/SettingsPage/Password/index.tsx
- Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
- Servers/routes/user.route.ts
problems with validations and loading the data inside inputs is fixed
Now, the only things are left is Team Tab and Uploading profile image
> 056 dec 17 enhancements

- Clients/src/presentation/components/CreateProjectForm/index.tsx
Users' emails are added on the Owner dropdown on create project modal
Addressing to close #389
> Users' emails are added on the dropdown as well

- Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.tsx
- Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
- Clients/src/presentation/components/AddNewRiskForm/index.tsx
- Clients/src/presentation/components/AddNewVendorRiskForm/index.tsx
- Clients/src/presentation/components/Breadcrumbs/index.tsx
- Clients/src/presentation/components/Charts/BarChart/index.tsx
- Clients/src/presentation/components/CreateProjectForm/index.tsx
- Clients/src/presentation/components/Fallback/index.tsx
Documentation for components is added
> 061 jan 9 component documentations

- Servers/flags.ts
> Revert flag

- Clients/src/presentation/components/Inputs/Autocomplete/index.md
- Clients/src/presentation/components/Inputs/Checkbox/index.md
- Clients/src/presentation/components/Inputs/Datepicker/index.md
- Clients/src/presentation/components/Inputs/Dropdowns/index.md
- Clients/src/presentation/components/Inputs/Field/index.md
- Clients/src/presentation/components/Inputs/Image/index.md
- Clients/src/presentation/components/Inputs/Radio/index.md
- Clients/src/presentation/components/Inputs/Select/index.md
- Clients/src/presentation/components/Label/BaseLabel/index.md
Readme files for more components is added
Addressing issue #439
> doc for components

- Servers/documentation/driver/autoDriver.md
- Added documentation for `autoDriver` utility for BE.
NA
> 063 Jan 10: Documentation for Auto Driver for Backend

- Clients/src/application/hooks/useProjectStatus.tsx
- Clients/src/presentation/pages/Home/index.tsx
- Servers/mocks/subtopic.mock.data.ts
- Servers/mocks/topic.mock.data.ts
There was lots of bugs in casting and assigning data types and error handlings which turned the dashboard blank.
These are some of the outer layers of errors
> 063 jan 10 bug fix

- Clients/src/presentation/pages/Home/index.tsx
- Clients/src/presentation/pages/index.tsx
- Clients/src/presentation/vw-v2-components/Skeletons/index.tsx
This component functions as a placeholder (Loading indicator) for components that are waiting to fetch data
@gorkemcetin  I hope its visible enough 😁
Its a nice thing to use instead of showing texts like "Loading..."
https://github.com/user-attachments/assets/b7ca4df5-ded2-4fac-a033-7107b3bb14b1
> 065 jan 12 vw components

- Clients/src/presentation/components/Table/WithPlaceholder/index.tsx
- Clients/src/presentation/mocks/vendors/vendors.data.ts
- Clients/src/presentation/pages/ProjectView/Overview/index.tsx
- Clients/src/presentation/pages/Vendors/index.tsx
- Servers/driver/autoDriver.driver.ts
> 066 jan 14 db network fix

- Clients/clean-architecture.md
Briefly describing the design pattern we've used, Clean Architecture, is our Clients folder
Addressing to close #441
> Clean Architecture Readme is added

- Clients/src/presentation/mocks/compliance.data.ts
- Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
- Clients/src/presentation/pages/ComplianceTracker/index.css
The calculations inside Cards are done
addressing to close #394
> 069 jan 16 compliance tracker calcs

- Clients/src/presentation/pages/Assessment/index.tsx
- Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
Assessments Tracker Calculations Cards are Done
Addressing to close #397
> Assessments Tracker Calculations

- Clients/src/application/repository/entity.repository.ts
- Clients/src/infrastructure/api/networkServices.ts
The `authToken` is passed as default value in the `entity.repository.ts` now.
> 070 jan 17 adding auth token

- Clients/src/presentation/pages/Assessment/index.tsx
As we discussed, I changed what we're naming each box
> Assessment values fixed

- Clients/src/application/contexts/VerifyWise.context.ts
The was a mismatch between type in Context and App.tsx
> Fixed the context

- Clients/src/presentation/pages/index.tsx
- Clients/src/presentation/vw-v2-components/Checks/index.tsx
The new Checkbox, VWCheckbox is added
> VWCheckbox, new checkbox component is added

- Servers/controllers/role.ctrl.ts
- Servers/swagger.yaml
- Servers/utils/role.utils.ts
- Servers/utils/vendor.utils.ts
- Updated the swagger and util files to fix 500 error and match the fields in the db
CC: @charurajput16 
NA
> 079 Jan 21: Fix 500 error in Vendors and other models

- Clients/src/App.tsx
https://github.com/user-attachments/assets/9e96769c-f9a9-4230-9997-94917af5e3a1
> Route protection enabled

- Clients/src/presentation/components/Inputs/Checkbox/index.tsx
- Clients/src/presentation/pages/Authentication/Login/index.tsx
Checkbox was not selectable. Now it is. To help you with pushing the task forward, I fixed the UI part.
Please complete the logic @salmanja (You'll need to make it keep the data for 30 days now)
https://github.com/user-attachments/assets/719ad8f8-26b9-41fb-aa10-4a896c5f8a7d
> Check box is now selectable

- Clients/src/presentation/pages/Home/index.tsx
Add project button was missing in the dashboard for the empty state
Before
After
> Add create project button for empty state

- Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
- Servers/endpoints-test/assessment.http.test.rest
Fixing the padding/margin/spacing bug
I tried to push your task forward guys (@charurajput16 , @eieimon , @melpsh )
> 078 jan 28 fix enhancement

- Clients/src/infrastructure/api/customAxios.ts
- Clients/src/presentation/components/FileUpload/index.tsx
- Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
The bug for components position if fixed now.
https://github.com/user-attachments/assets/cb261dae-0739-44ab-9e8e-c5ac4ba7d328
> File upload component fixed

- Clients/src/presentation/pages/index.tsx
- Clients/src/presentation/vw-v2-components/Toast/index.tsx
> Toast component

- Clients/src/presentation/vw-v2-components/Toast/index.tsx
> Toast centered

- Clients/src/App.tsx
- Clients/src/application/tools/extractToken.ts
Now userId is being fetched from db
> Replacing userId with dynamic value

- Clients/src/App.tsx
- Clients/src/application/repository/entity.repository.ts
- Clients/src/presentation/components/ProtectedRoute/index.tsx
- If there's no user in the database, only admin-reg is accessible.
- If there's any user in the database, admin-reg is no longer accessible
> 082 feb 1 one time admin reg

- Servers/endpoints-test/vwmailer.http.rest
- Servers/index.ts
- Servers/routes/vwmailer.route.ts
- Servers/services/emailService.ts
Now, emails for inviting users and password reset is added on the server side.
> 083 feb 2 VWMailer Service

- Servers/database/db.ts
- Servers/index.ts
> Checking tables fixed

- Clients/src/presentation/pages/Authentication/RegisterAdmin/index.tsx
> Fixing navigation after registration

- Clients/src/application/hooks/useProjectData.tsx
- Clients/src/application/hooks/useProjectRisks.tsx
- Clients/src/application/hooks/useVendorRisks.tsx
- Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
- Clients/src/presentation/pages/ProjectView/index.tsx
- Servers/controllers/projectRisks.ctrl.ts
- Servers/controllers/vendorRisk.ctrl.ts
- Servers/routes/projectRisks.route.ts
- Servers/routes/vendorRisk.route.ts
- Servers/utils/projectRisk.utils.ts
- Servers/utils/vendorRisk.util.ts
Get for projectRisks and vendorRisks from database pg complete
> ProjectRisks & VendorRisks CRUD

- Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.tsx
- Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
- Clients/src/presentation/components/AddNewRiskForm/styles.module.css
- Clients/src/presentation/components/FileUpload/types.ts
- Clients/src/presentation/components/Table/index.tsx
- Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
- Clients/src/presentation/pages/ProjectView/index.tsx
> 085 fix crud bug

- Clients/src/presentation/components/Inputs/Select/index.tsx
> Small bug fix

- Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
- Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
- Clients/src/presentation/components/Modals/Controlpane/paneInterfaces.ts
- Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
- Servers/controllers/control.ctrl.ts
- Servers/controllers/subcontrol.ctrl.ts
- Servers/endpoints-test/control.http.test.rest
- Servers/routes/control.route.ts
- Servers/utils/subControl.utils.ts
Progress in trying to load data of controls and sub controls into the control pane
> 086 complaince tracker crud

- Clients/src/application/repository/entity.repository.ts
- Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
- Clients/src/presentation/components/Inputs/Field/index.tsx
- Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
- Clients/src/presentation/pages/Authentication/Login/index.tsx
- Passing values to load into control pane
- fixing text field overflow
- removing signup link
Addressing to close #738 
close #739
> Enhancements

- Clients/src/application/hooks/useProjectData.tsx
- Clients/src/application/repository/entity.repository.ts
- Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
- Servers/controllers/user.ctrl.ts
Now, user name and surname updates successfullt
Addressing to close #760
> User detail update complete

- Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
- Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
- Clients/src/presentation/components/Modals/Controlpane/paneInterfaces.ts
- Clients/src/presentation/components/Sidebar/index.tsx
- Clients/src/presentation/components/Table/AccordionTable/index.tsx
- Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
- Servers/controllers/control.ctrl.ts
- Servers/utils/control.utils.ts
- Servers/utils/controlCategory.util.ts
- Servers/utils/subControl.utils.ts
- Servers/utils/user.utils.ts
Saving controls in database and handling different scenarios.
- if controls category exists or not
- if control already exists or not
- etc.
> 088 feb 7 complaice crud

- Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
- Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
- Clients/src/presentation/components/Modals/Controlpane/paneInterfaces.ts
- Clients/src/presentation/components/Table/AccordionTable/index.tsx
- Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
- SQL_Commands.sql
- Servers/controllers/control.ctrl.ts
- Servers/controllers/controlCategory.ctrl.ts
- Servers/controllers/subcontrol.ctrl.ts
- Servers/index.ts
- Servers/routes/control.route.ts
- Servers/routes/controlCategory.route.ts
- Servers/utils/control.utils.ts
- Servers/utils/controlCategory.util.ts
- Servers/utils/subControl.utils.ts
Fixing updates on their way...
> 090 dynamic compliance real data

- Clients/src/application/validations/formValidation.ts
- Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
Files header removed from assessment tracker, min char for name is 2 now
> Small changes

- Clients/src/App.tsx
- Clients/src/presentation/components/Cards/StatsCard/index.tsx
- Clients/src/presentation/components/Cards/StatsCard/style.ts
- Clients/src/presentation/components/ProjectCard/ProgressBar/index.tsx
- Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
- Clients/src/presentation/pages/index.tsx
> 099 feb 15 new cards

- Clients/src/presentation/components/Cards/StatsCard/index.tsx
- Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
- Clients/src/presentation/pages/index.tsx
- Clients/src/presentation/vw-v2-components/Skeletons/index.tsx
> Small details for compliance tracker

- Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
- Clients/src/presentation/components/Sidebar/index.tsx
- Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
> 100 feb 16 bug fix enhancement

- Clients/src/App.tsx
- Clients/src/application/hooks/useAssessmentAnswers.tsx
- Clients/src/domain/Question.ts
- Clients/src/domain/Subtopic.ts
- Clients/src/presentation/components/Question/index.tsx
- Clients/src/presentation/pages/Assessment/1.0AssessmentTracker/questions.tsx
- Clients/src/presentation/pages/Assessment/NewAssessment/AllAssessments.tsx
- Servers/controllers/project.ctrl.ts
- Servers/controllers/question.ctrl.ts
- Servers/routes/question.route.ts
- Servers/utils/question.utils.ts
Questions can be answered and fetched. Functions correctly.
> Answering questions

- Clients/src/App.tsx
- Clients/src/domain/ControlCategory.ts
- Clients/src/presentation/components/Modals/ComplianceFeedback/ComplianceFeedback.tsx
- Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
- Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlCategory.tsx
- Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlsTable.tsx
- Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/index.css
- Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/index.tsx
- Clients/src/presentation/pages/ComplianceTracker/NewComplianceTracker.tsx
- Clients/src/presentation/pages/index.tsx
- Servers/controllers/control.ctrl.ts
Now, Compliance Tracker's dynamic structure is complete.
> 103 feb 22 dynamic compliance

- Clients/src/presentation/components/ProjectCard/ProgressBar/index.tsx
- Clients/src/presentation/vw-v2-components/Buttons/index.tsx
> 104 feb 23 enhanced components

- Clients/src/presentation/pages/ProjectView/Overview/index.tsx
- Clients/src/presentation/pages/ProjectView/index.tsx
> 105 feb 25 removing vendorRisks tab

- Clients/src/presentation/pages/Home/1.0Home/index.tsx
> small null value fixed

- Clients/src/application/validations/stringValidation.ts
- Clients/src/presentation/components/Alert/index.tsx
- Clients/src/presentation/components/Cards/ProjectCard/style.ts
- Clients/src/presentation/pages/Home/1.0Home/index.tsx
- Clients/src/presentation/vw-v2-components/Forms/ProjectForm/index.tsx
- Clients/src/presentation/vw-v2-components/Forms/ProjectForm/style.ts
> 105.5 feb 25 fix project card

- Clients/src/App.tsx
- Clients/src/presentation/components/Cards/ProjectCard/index.tsx
- Clients/src/presentation/pages/Home/1.0Home/index.tsx
- Clients/src/presentation/pages/ProjectView/V1.0ProjectView/Overview/index.tsx
- Clients/src/presentation/pages/ProjectView/V1.0ProjectView/Overview/style.ts
- Clients/src/presentation/pages/ProjectView/V1.0ProjectView/index.tsx
- Clients/src/presentation/pages/ProjectView/V1.0ProjectView/style.ts
- Clients/src/presentation/pages/ProjectView/index.tsx
The new overview tab inside project view.
Values are hard-coded. next step is to fetch the dynamic data based on the project id.
> New project view: Overview Tab

- Clients/src/domain/User.ts
- Clients/src/presentation/components/Cards/DescriptionCard/index.tsx
- Clients/src/presentation/components/Cards/DescriptionCard/style.ts
- Clients/src/presentation/components/Cards/InfoCard/index.tsx
- Clients/src/presentation/components/Cards/InfoCard/style.ts
- Clients/src/presentation/components/Cards/RisksCard/index.tsx
- Clients/src/presentation/components/Cards/RisksCard/style.ts
- Clients/src/presentation/components/Cards/TeamCard/index.tsx
- Clients/src/presentation/components/Cards/TeamCard/style.ts
- Clients/src/presentation/components/Sidebar/index.tsx
- Clients/src/presentation/pages/ProjectView/V1.0ProjectView/Overview/index.tsx
- Clients/src/presentation/pages/ProjectView/V1.0ProjectView/Overview/style.ts
- Clients/src/presentation/pages/ProjectView/V1.0ProjectView/index.tsx
- Clients/src/presentation/pages/index.tsx
- Servers/endpoints-test/project.http.test.rest
All parts are dynamic now
https://github.com/user-attachments/assets/a86e1cd3-88b9-477e-82bc-eaf3aafb3988
> Refactored project overview tab

- Clients/src/presentation/pages/Home/1.0Home/index.tsx
> 106.1 feb 28 refactor project view

- Clients/src/presentation/pages/Home/1.0Home/index.tsx
> handling undefined values

- Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
- Clients/src/presentation/pages/ProjectView/V1.0ProjectView/ProjectRisks/index.tsx
- Clients/src/presentation/pages/ProjectView/V1.0ProjectView/index.tsx
- Clients/src/presentation/pages/ProjectView/index.tsx
- Clients/src/presentation/vw-v2-components/Table/index.tsx
> Project view, Settings tab added

- Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
Now, VWToast gets closed after deleting is complete and navigation to dashboard is done.
https://github.com/user-attachments/assets/47cb7a67-5340-4708-9445-c6ec7034922e
> Deleting project

- Clients/src/presentation/pages/SettingsPage/Password/index.tsx
- Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
- Clients/src/presentation/pages/SettingsPage/Team/index.tsx
- Clients/src/presentation/pages/SettingsPage/index.tsx
- Clients/src/presentation/pages/SettingsPage/style.ts
- Clients/src/presentation/vw-v2-components/Dialogs/DualButtonModal/index.tsx
@srwa-rsp to push your tasks on the settings page forward, I completed some of the UI details.
> Small UI details in the Settings

- Clients/src/presentation/pages/SettingsPage/Password/index.tsx
- Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
- Clients/src/presentation/pages/SettingsPage/Team/index.tsx
- Clients/src/presentation/pages/SettingsPage/index.tsx
- CC: Pushing Settings related issues forward for you on details.
> Mo 108 mar 6 refactor enhancement

- Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
- Clients/src/presentation/vw-v2-components/Skeletons/index.tsx
- Clients/src/presentation/vw-v2-components/Toast/index.tsx
All the items related to Profile tab is complete.
> Settings/profile tab, complete

- Clients/src/presentation/pages/SettingsPage/Password/index.tsx
- Servers/controllers/user.ctrl.ts
- Servers/routes/user.route.ts
Details of the password tab is complete now.
> Password tab completed

- Servers/index.ts
**Hello buddy!** is removed now
> Changing root dir welcome message

- Clients/src/presentation/components/AddNewRiskForm/index.tsx
- Clients/src/presentation/components/Modals/Controlpane/NewControlPane.tsx
- Clients/src/presentation/components/Modals/NewRisk/index.tsx
- Clients/src/presentation/components/Modals/NewVendor/index.tsx
- Clients/src/presentation/pages/Vendors/index.tsx
Tabs and most of Modal buttons now have the same theme as other parts (Green)
> Mo 112 mar 12 modals tabs

- Clients/src/presentation/pages/Home/1.0Home/index.tsx
The codebase for dashboard is now enhanced regarding readability and performance.
----
Here are things that could be better and I did:
1. **TypeScript Types:** The state variables and function parameters could benefit from more specific TypeScript types instead of using `any`. This would improve type safety and code readability.
2. **Code Duplication:** There is some duplication in the rendering of `SmallStatsCard` components. This could be refactored into a separate function or component to reduce redundancy.
3. **Magic Numbers:** The code contains some magic numbers (e.g., **3000** for timeouts). These could be replaced with named constants to improve readability.
4. Error Handling: While errors are logged and alerts are shown, it might be beneficial to provide more user-friendly error …
> Enhancing codebase for the Dashboard

- Clients/src/presentation/pages/Home/1.0Home/index.tsx
Reverts bluewave-labs/verifywise#947
> Revert "Enhancing codebase for the Dashboard"

- Clients/src/App.tsx
- Clients/src/application/contexts/VerifyWise.context.ts
- Clients/src/presentation/containers/Dashboard/index.tsx
- Clients/src/presentation/pages/Home/1.0Home/index.tsx
- Clients/src/presentation/vw-v2-components/Forms/ProjectForm/index.tsx
Now, when ever a new project is added or demo data is added, it quickly appears on the selector as well
> Mo 114 mar 12 sidebar selector

- Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
Change the border color of the disabled button
#879
> #879 QA/QC - Settings

- Servers/controllers/project.ctrl.ts
> Fixing mis-calculation for assessments completed

- Clients/src/presentation/pages/SettingsPage/Profile/index.tsx
- Servers/controllers/user.ctrl.ts
- Servers/utils/user.utils.ts
Surname was unable to update. Now it is fixed
These are the parts that were missing from the query
> Fixing surname update

- Clients/src/application/hooks/useFetchProjects.ts
- Clients/src/application/interfaces/appStates.ts
- Clients/src/application/interfaces/iprogress.ts
- Clients/src/application/tools/log.engine.ts
- Clients/src/presentation/pages/Home/1.0Home/index.tsx
- Enhancing Insert demo data button condition
- Add Proper TypeScript Interfaces
- Extract Business Logic into Custom Hooks
- Implement Proper Types
> Mo 120 april 13 enhancing files

- Clients/src/domain/enums/mitigitaion.ts
- Clients/src/domain/interfaces/iAlert.ts
- Clients/src/domain/interfaces/iForm.ts
- Clients/src/domain/interfaces/iResponse.ts
- Clients/src/domain/interfaces/iRiskForm.ts
- Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.tsx
- Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
- Clients/src/presentation/components/AddNewRiskForm/index.tsx
- Clients/src/presentation/components/AddNewRiskForm/style.ts
- Clients/src/presentation/components/AddNewVendorRiskForm/index.tsx
In this pull request, I organized the codebase, moved interfaces to where they needs to be, and improved type safety
> Mo 125 may 2 modifications enhancements

- Clients/src/domain/interfaces/iMetricSection.ts
- Clients/src/domain/interfaces/iSelect.ts
- Clients/src/domain/interfaces/iWidget.ts
- Clients/src/presentation/components/Inputs/Dropdowns/index.tsx
- Clients/src/presentation/components/Inputs/Dropdowns/style.ts
- Clients/src/presentation/components/Inputs/Field/index.tsx
- Clients/src/presentation/components/Inputs/Image/constants.ts
- Clients/src/presentation/components/Inputs/Image/index.tsx
- Clients/src/presentation/components/Inputs/Select/index.tsx
- Clients/src/presentation/components/MetricSection/index.tsx
- Clients/src/presentation/components/Modals/Banner/index.tsx
- Clients/src/presentation/components/Modals/Banner/style.ts
- Clients/src/presentation/components/Modals/Basic/index.tsx
- Clients/src/presentation/components/Modals/Basic/style.ts
- Inputs/dropdowns, separating interfaces and hard-coded value
- Inputs/field, separating interfaces and hard-coded value
- Inputs/ImageField, separating interfaces and hard-coded value
- Inputs/Radio, separating interfaces and hard-coded value
- Inputs/Select, separating interfaces and hard-coded value
- Inputs/MetricSection, separating interfaces and hard-coded value
- Inputs/Modals/Banner, separating interfaces and hard-coded value
- Inputs/Modals/Basic, separating interfaces and hard-coded value
Fixes #123
> Mo 128 may 6 type definition

- Servers/database/migrations/20250502184633-create-structure-for-assessment-tracker.js
- Servers/database/migrations/20250502184712-create-structure-for-compliance-tracker.js
- Servers/database/migrations/20250508221800-add-ISO-42001-framework.js
- Servers/database/migrations/20250508222038-add-clauses-ISO-42001.js
- Servers/database/migrations/20250509022034-add-annex-ISO-42001.js
- Servers/structures/ISO-42001/annex/annex.struct.ts
- Servers/structures/ISO-42001/annex/annexcategories/05-organizational-policies-and-governance.annexcategory.ts
- Servers/structures/ISO-42001/clauses/clauses.struct.ts
- Servers/structures/ISO-42001/clauses/subclauses/04-context-of-organization.subclause.ts
- Servers/structures/ISO-42001/clauses/subclauses/05-leadership.subclause.ts
- Servers/tsconfig.json
- Added migration script to:
- Add a new framework in `frameworks` table
- Create tables and structure data for clauses
- Create tables and structure data for annex
Fixes #1322
> Add migration script to create ISO 42001 structure

- Clients/src/infrastructure/api/customAxios.ts
- Servers/controllers/user.ctrl.ts
- Servers/index.ts
- Servers/swagger.yaml
> Sam 08 apr merge api routes into master

- Servers/index.ts
> fix: add 'allowedHeaders' to CORS configuration for improved security

- Clients/src/presentation/components/Drawer/ClauseDrawerDialog/index.tsx
- Clients/src/presentation/pages/ISO/Clause/clause.structure.ts
- Clients/src/presentation/pages/ISO/Clause/index.tsx
- Clients/src/presentation/pages/index.tsx
Clause form UI implementation with hard-coded values is completed. 
Next steps on this page will be:
1. Loading dynamic values
2. Making CRUD operations work
3. separating constants and values
https://github.com/user-attachments/assets/ec29f9a9-063c-4717-91a9-aced57f01805
> Mo 130 may 10 iso modals

- Clients/src/presentation/components/Drawer/AnnexDrawerDialog/index.tsx
- Clients/src/presentation/pages/ISO/Annex/index.tsx
Annex control form is completed UI wise.
https://github.com/user-attachments/assets/72433b79-5946-4f60-99cd-5f0e21394af0
> Mo 131 may 11 annexes drawer form

- Servers/controllers/reporting.ctrl.ts
Now, report generation works
Fixes #123
> Report generation bug fixed

- Clients/package-lock.json
- Clients/package.json
- Clients/src/presentation/pages/ISO/AiImplemented/AiGeneratedISO42001Annexes.tsx
- Clients/src/presentation/pages/ISO/AiImplemented/AiGeneratedISO42001Clauses.tsx
- Clients/src/presentation/pages/ProjectView/ProjectFrameworks/index.tsx
I asked Cursor to implement ISO framework clauses and annexes with respect to what we've done in EU AI Act and be creative in it and here's how it's done
Make sure you install framer-motion package in the frontend:
`npm i framer-motion`
https://github.com/user-attachments/assets/b5eb927a-906b-4290-a15b-41502178d5a0
> Mo 132 may 12 ai implemented iso

- Servers/controllers/reporting.ctrl.ts
- Servers/utils/fileUpload.utils.ts
- Servers/utils/reporting.utils.ts
Now the bug for generating reports and loading them inside the table and removing them is fixed
Fixes #123
> Report generate and remove fixed

- Servers/controllers/iso42001.ctrl.ts
- Servers/controllers/projectRisks.ctrl.ts
- Servers/database/migrations/20250514000706-add-file-sources-for-ISO42001.js
- Servers/index.ts
- Servers/models/file.model.ts
- Servers/routes/iso42001.route.ts
- Servers/routes/projectRisks.route.ts
- Servers/utils/fileUpload.utils.ts
- Servers/utils/iso42001.utils.ts
- Servers/utils/projectRisk.utils.ts
- Added PATCH routes for saving clauses and annexes
- `PATCH /saveClauses`
- `PATCH /saveAnnexes`
Fixes #
> Add PATCH route for ISO 42001

- Servers/controllers/iso42001.ctrl.ts
- Servers/routes/iso42001.route.ts
- Servers/utils/eu.utils.ts
- Servers/utils/iso42001.utils.ts
- Servers/utils/project.utils.ts
- Added DELETE routes for ISO
- `DELETE /iso-42001/:id`: Delete ISO framework for a project based on project id
- Updated `DELETE /project/:id` to delete iso framework when the project is deleted
Fixes #
> Add DELETE routes for ISO

- Servers/controllers/iso42001.ctrl.ts
- Servers/package-lock.json
- Servers/package.json
- Servers/routes/iso42001.route.ts
- Servers/utils/iso42001.utils.ts
- Servers/validations/id.valid.ts
- Added GET routes for ISO 42001
- `GET /iso-42001/clauses`: Get all the clauses list
- `GET /iso-42001/annexes`: Get all the annexes list
- `GET /iso-42001/subClauses/byClauseId/<id>`: Get the subclauses list for clause id
- `GET /iso-42001//annexCategories/byAnnexId/<id>`: Get annex categories list for annex id
- `GET /iso-42001/clauses/byProjectId/<project-framework-id>`: Get all clauses, subclauses for project framework id
- `GET /iso-42001/annexes/byProjectId/<project-framework-id>`: Get all annex categories for project framework id
- `GET /iso-42001/subClause/byId/1?projectFrameworkId=<project-framework-id>`: Get subclause by id for project framework id
- `GET /iso-42001/annexCategory/byId/1?projectFrameworkId=<project-framework-id>`: Get annex category by id for project framework …
> Add GET routes for ISO

- Servers/controllers/framework.ctrl.ts
- Servers/controllers/iso42001.ctrl.ts
- Servers/routes/frameworks.route.ts
- Servers/routes/iso42001.route.ts
- Servers/utils/framework.utils.ts
- Added route to delete framework from a project
- `DELETE /frameworks/fromProject?projectId=<project-id>&frameworkId=<framework-id>`
Fixes #1386
> Add route to delete framework from project

- Clients/src/App.tsx
- Clients/src/application/hooks/useFrameworks.ts
- Clients/src/application/redux/getAuthToken.ts
- Clients/src/application/repository/clause_struct_iso.repository.ts
- Clients/src/application/repository/entity.repository.ts
- Clients/src/domain/interfaces/iRequestParams.ts
- Clients/src/domain/types/RootState.ts
- Clients/src/presentation/components/Drawer/ClauseDrawerDialog/index.tsx
- Clients/src/presentation/pages/Home/1.0Home/index.tsx
- Clients/src/presentation/pages/ISO/Annex/index.tsx
- Clients/src/presentation/pages/ISO/Clause/index.tsx
- Clients/src/presentation/pages/ProjectView/AddNewFramework/index.tsx
- Clients/src/presentation/pages/ProjectView/ProjectFrameworks/index.tsx
- Servers/database/migrations/20250502184525-create-table-for-frameworks.js
- Servers/database/migrations/20250508221800-add-ISO-42001-framework.js
- Servers/endpoints-test/projects.http.test.rest
- Servers/routes/project.route.ts
Read operation on the Clauses tab is done.
Addressing the issue #602 
https://github.com/user-attachments/assets/81de4903-7fac-49c3-a73e-1c2b20d4fd83
> Mo 135 may 17 integrating iso42001

- Servers/controllers/eu.ctrl.ts
- Servers/controllers/iso42001.ctrl.ts
- Servers/routes/iso42001.route.ts
- Servers/utils/iso42001.utils.ts
- Added calculation endpoints for ISO
- `GET /iso-42001/clauses/progress/<project-framework-id>`: Get clauses progress by project framework id
- `GET /iso-42001/annexes/progress/<project-framework-id>`: Get annexes progress by project framework id
- `GET /iso-42001/all/clauses/progress`: Get progress for all clauses
- `GET /iso-42001/all/annexes/progress`: Get progress for all annexes
Fixes #1413
> Add calculations endpoints for ISO

- README.md
Provide a concise description of the changes made and their intended purpose.
> Merging develop into master: June 12

- Clients/src/application/hooks/useProjectData.tsx
- Clients/src/application/hooks/useRegisterUser.tsx
- Clients/src/application/repository/annexCategory_iso.repository.ts
- Clients/src/application/repository/annex_struct_iso.repository.ts
- Clients/src/application/repository/entity.repository.ts
- Clients/src/application/repository/organization.repository.ts
- Clients/src/infrastructure/api/networkServices.ts
- Clients/src/presentation/components/AddNewRiskForm/index.tsx
- Clients/src/presentation/components/AddNewVendorRiskForm/index.tsx
- Clients/src/presentation/components/Cards/SmallStatsCard/index.tsx
- Clients/src/presentation/components/Drawer/ClauseDrawerDialog/index.tsx
- Clients/src/presentation/components/IconButton/index.tsx
- Clients/src/presentation/components/Modals/Controlpane/index.tsx
- Clients/src/presentation/components/ProtectedRoute/index.tsx
- Clients/src/presentation/components/VWQuestion/index.tsx
- Clients/src/presentation/pages/Assessment/NewAssessment/AssessmentQuestions/AssessmentQuestions.tsx
- Clients/src/presentation/pages/Authentication/Login/index.tsx
- Clients/src/presentation/pages/Authentication/RegisterAdmin/index.tsx
- Clients/src/presentation/pages/Authentication/RegisterUser/index.tsx
- Clients/src/presentation/pages/Home/index.tsx
- Clients/src/presentation/pages/ISO/Clause/index.tsx
- Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
- Clients/src/presentation/pages/ProjectView/index.tsx
- Servers/scripts/resetDatabase.ts
Almost all the unnecessary `console.log()`s are removed. The only places that there are still left are where they act as a placeholder.
> Mo 154 jun 24 removing console.logs

- Clients/src/application/hooks/useProjectData.tsx
- Clients/src/application/hooks/useRegisterUser.tsx
- Clients/src/application/repository/annexCategory_iso.repository.ts
- Clients/src/application/repository/annex_struct_iso.repository.ts
- Clients/src/application/repository/entity.repository.ts
- Clients/src/application/repository/organization.repository.ts
- Clients/src/infrastructure/api/networkServices.ts
- Clients/src/presentation/components/AddNewRiskForm/index.tsx
- Clients/src/presentation/components/AddNewVendorRiskForm/index.tsx
- Clients/src/presentation/components/Cards/SmallStatsCard/index.tsx
- Clients/src/presentation/components/Drawer/ClauseDrawerDialog/index.tsx
- Clients/src/presentation/components/IconButton/index.tsx
- Clients/src/presentation/components/Modals/Controlpane/index.tsx
- Clients/src/presentation/components/ProtectedRoute/index.tsx
- Clients/src/presentation/components/VWQuestion/index.tsx
- Clients/src/presentation/pages/Assessment/NewAssessment/AssessmentQuestions/AssessmentQuestions.tsx
- Clients/src/presentation/pages/Authentication/Login/index.tsx
- Clients/src/presentation/pages/Authentication/RegisterAdmin/index.tsx
- Clients/src/presentation/pages/Authentication/RegisterUser/index.tsx
- Clients/src/presentation/pages/Home/index.tsx
- Clients/src/presentation/pages/ISO/Clause/index.tsx
- Clients/src/presentation/pages/ProjectView/RisksView/index.tsx
- Clients/src/presentation/pages/ProjectView/index.tsx
- Servers/scripts/resetDatabase.ts
Reverts bluewave-labs/verifywise#1696
> Revert "Mo 154 jun 24 removing console.logs"

- Servers/controllers/user.ctrl.ts
- Servers/domain.layer/models/user/user.model.ts
More User class dependencies including user update is added
> More User class dependencies including user update is added

- Servers/controllers/eu.ctrl.ts
- Servers/controllers/iso42001.ctrl.ts
- Servers/controllers/project.ctrl.ts
- Servers/domain.layer/enums/ai-risk-classification.enum.ts
- Servers/domain.layer/enums/high-risk-role.enum.ts
- Servers/domain.layer/interfaces/i.project.ts
- Servers/domain.layer/interfaces/i.projectFramework.ts
- Servers/domain.layer/models/project/project.mock.data.ts
- Servers/domain.layer/models/project/project.model.ts
- Servers/domain.layer/tests/project.model.spec.ts
- Servers/driver/autoDriver.driver.ts
- Servers/utils/project.utils.ts
Now, Project entity is also following class-based approach and has its own unit tests
Addressing to close #1712
> Mo 157 jun 28 class based project

- Servers/domain.layer/tests/assessment.model.spec.ts
Unit tests for Assessment Model added and all passed
> Assessment unit tests added

- Servers/controllers/projectRisks.ctrl.ts
Fixing project risk update bug
> Fixing project risk update bug

- Clients/src/presentation/components/Modals/NewModelInventory/index.tsx
- Clients/src/presentation/pages/ModelInventory/ModelInventorySummary.tsx
- Clients/src/presentation/pages/ModelInventory/index.tsx
- Clients/src/presentation/pages/ModelInventory/modelInventoryTable.tsx
- Clients/src/presentation/pages/ModelInventory/style.ts
> Mo 196 aug 13 model inventory fixes

- Servers/domain.layer/frameworks/ISO-27001/ISO27001AnnexControlRisks.model.ts
- Servers/domain.layer/frameworks/ISO-27001/iso27001AnnexControl.model.ts
- Servers/domain.layer/interfaces/i.ISO27001Clause.ts
- Servers/domain.layer/interfaces/i.iso27001AnnexControl.ts
- Servers/domain.layer/models/frameworks/frameworks.model.ts
- Servers/domain.layer/tests/ISO27001AnnexCategory.model.spec.ts
> Mo 198 aug 14 bug fix

- Servers/controllers/iso27001.ctrl.ts
- Servers/routes/iso27001.route.ts
- Added routes and controllers for ISO 27001
> Added routes and controllers for ISO 27001

- Clients/src/application/repository/subtopic.repository.ts
**Refactor: Restructure and expand subtopic  repository**
This PR restructures the subtopic repository to improve code organization and expand functionality. The changes include:
Fixes #650
> add subtopic repository

- Clients/src/application/repository/subcontrol.repository.ts
**Refactor: Restructure and expand subcontrol  repository**
This PR restructures the subcontrol  repository to improve code organization and expand functionality. The changes include:
Fixes #649
> add subcontrol repository

- Clients/src/application/repository/role.repository.ts
**Refactor: Restructure and expand role repository**
This PR restructures the role repository to improve code organization and expand functionality. The changes include:
Fixes #648
> refactor: restructure and expand role repository

- Clients/src/application/repository/question.repository.ts
- Clients/src/presentation/components/VWQuestion/index.tsx
**Refactor: Restructure and expand question repository**
This PR restructures the question repository to improve code organization and expand functionality. The changes include:
Fixes #647
> refactor: restructure and expand question repository

- Clients/src/application/repository/projectScope.repository.ts
**Refactor: Restructure and expand project scope repository**
This PR restructures the project scope repository to improve code organization and expand functionality. The changes include:
Fixes #646
> add project scope repo

- Clients/src/application/hooks/useProjectRisks.tsx
- Clients/src/application/repository/projectRisk.repository.ts
- Clients/src/presentation/pages/ProjectView/V1.0ProjectView/ProjectRisks/index.tsx
**Refactor: Restructure and expand project risk repository**
This PR restructures the project risk repository to improve code organization and expand functionality. The changes include:
Fixes #645
> refactor: restructure and expand project risk repository

- Clients/src/application/hooks/useUserFilesMetaData.ts
- Clients/src/application/repository/file.repository.ts
- Clients/src/application/tools/fileDownload.ts
**Refactor: Restructure and expand file repository**
This PR restructures the file repository to improve code organization and expand functionality. The changes include:
Fixes #643
> refactor: restructure and expand file repository

- Clients/src/application/repository/controlCategory_eu_act.repository.ts
**Refactor: Restructure and expand control category repository**
This PR restructures the control category repository to improve code organization and expand functionality. The changes include:
Fixes #642
> refactor: restructure and expand control category repository

- Clients/src/presentation/components/Breadcrumbs/PageBreadcrumbs.tsx
- Clients/src/presentation/components/Breadcrumbs/index.tsx
- Clients/src/presentation/components/Breadcrumbs/routeMapping.ts
- Clients/src/presentation/pages/AITrustCenter/index.tsx
- Clients/src/presentation/pages/FairnessDashboard/FairnessDashboard.tsx
- Clients/src/presentation/pages/FileManager/index.tsx
- Clients/src/presentation/pages/Home/index.tsx
- Clients/src/presentation/pages/ModelInventory/index.tsx
- Clients/src/presentation/pages/ProjectView/V1.0ProjectView/index.tsx
- Clients/src/presentation/pages/ProjectView/index.tsx
- Clients/src/presentation/pages/Reporting/index.tsx
- Clients/src/presentation/pages/SettingsPage/index.tsx
- Clients/src/presentation/pages/TrainingRegistar/index.tsx
- Clients/src/presentation/pages/Vendors/index.tsx
- Clients/src/presentation/pages/WatchTower/index.tsx
- Clients/src/presentation/pages/index.tsx
Breadcrumbs added to the dashboard
> Breadcrumbs added to the dashboard

- Clients/src/presentation/pages/Framework/index.tsx
> Framework button replaced

- Servers/driver/autoDriver.driver.ts
> Fix auto drivers

- Clients/src/domain/types/Project.ts
- Clients/src/presentation/pages/Framework/ISO27001/Annex/index.tsx
- Clients/src/presentation/pages/Framework/ISO27001/Clause/index.tsx
- Clients/src/presentation/pages/Framework/ISO42001/Annex/index.tsx
- Clients/src/presentation/pages/Framework/ISO42001/Clause/index.tsx
- Clients/src/presentation/pages/Framework/index.tsx
- Clients/src/presentation/pages/Home/1.0Home/index.tsx
- Clients/src/presentation/vw-v2-components/Forms/ProjectForm/constants.ts
- Clients/src/presentation/vw-v2-components/Forms/ProjectForm/index.tsx
- Servers/driver/autoDriver.driver.ts
- Servers/utils/autoDriver.utils.ts
- Servers/utils/iso27001.utils.ts
- Servers/utils/project.utils.ts
- Added the code to create a project if no organizational project exists
- Added code to delete organizational project
- Added code to add/remove organizational frameworks from organizational project
- Updated the create project model
> Update the UI for organizational frameworks

- Clients/src/domain/types/Framework.ts
- Clients/src/presentation/pages/ProjectView/ProjectFrameworks/index.tsx
- Updated frameworks list in non-organizational project view
Before
After
> Updated manage frameworks project view UI

- .claude/settings.local.json
- Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.md
- Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.tsx
- Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.md
- Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
- Clients/src/presentation/components/AddNewRiskForm/index.md
- Clients/src/presentation/components/AddNewRiskForm/index.tsx
Enhancing components using Claude Code
> Mo 208 sept 4 code quality

- Servers/scripts/createNewTenant.ts
- Fix organization creation bug
Fixes #2041
> Fix: Unable to create organization and register

- Clients/src/presentation/components/RiskLevel/RiskChip.tsx
- Clients/src/presentation/components/RiskLevel/constants.ts
- Clients/src/presentation/vw-v2-components/Table/VWProjectRisksTableBody.tsx
Replacing chips in projectRisks and vendorRisks
"Fixes #2033 " 
Scrrenshots attached for reference -
> replacing-chips-unifying-styling

- .github/workflows/docker-image-saas-test.yml
- .github/workflows/docker-image-saas.yml
- docker-compose.prod.yml
- install.sh
- Updated workflow to automate the SaaS deployment
- Added workflow to automatically deploy/update `test.verifywise.ai` on every push to `develop-saas`
> Automate the SaaS deployment

- Clients/src/presentation/components/AddNewRiskForm/MitigationSection/index.tsx
- Clients/src/presentation/components/AddNewRiskForm/RisksSection/index.tsx
- Clients/src/presentation/components/AddNewRiskForm/index.tsx
- Clients/src/presentation/components/Sidebar/index.tsx
- Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
- Clients/src/presentation/pages/ProjectView/V1.0ProjectView/ProjectRisks/index.tsx
- fixed the prop type error in your Sidebar component
- fixed the React key prop warning in the Project Settings component
- Now the 'Monitored regulations and standards' dropdown will only display EU AI Act
- fixed the MUI warning about out-of-range values in the select components
Addressing to close #2052 
Addressing to close #2053  
Addressing to close #2054
> Mo 209 sept 6 bug fix

- Servers/scripts/createNewTenant.ts
> Fix training registry bug

- Clients/src/presentation/components/Sidebar/index.tsx
- Commented Event Tracker for now
> Remove Event Tracker for now

- Clients/src/application/config/routes.tsx
- Clients/src/presentation/pages/DashboardOverview/WorkingDashboard.tsx
- Clients/src/presentation/pages/DashboardOverview/index.tsx
This PR implements a comprehensive dashboard with real-time metrics, replacing mock data with actual API integrations and following the established design system.
- **Real-time metric cards**: Projects, Trainings, Models, Reports, Evidences, Vendor Risks, Vendors, Users, Policies
- **Clean design**: Uses existing theme colors and card styles from the design system  
- **Responsive layout**: Proper grid layout with consistent spacing
- **Error handling**: Graceful fallbacks for API failures
- **Performance optimized**: Parallel API calls with Promise.allSettled
- `WorkingDashboard.tsx` - Main dashboard component with metric cards
- `useDashboardMetrics.ts` - Centralized hook for fetching dashboard data
- `/dashboard` - Core dashboard metrics (projects, trainings, models, reports)
- …
> Implement comprehensive dashboard with real-time metrics

- Clients/src/presentation/components/ProtectedRoute/index.tsx
- Clients/src/presentation/components/Sidebar/index.tsx
- Enable event tracker for OSS
> Enable event tracker for OSS

- Clients/src/presentation/components/Layout/PageHeader.tsx
- Clients/src/presentation/pages/Vendors/index.tsx
Content header separation
Fixes #2111
> Content Header Saperation

- Servers/utils/eu.utils.ts
- Servers/utils/iso27001.utils.ts
- Servers/utils/iso42001.utils.ts
- Servers/utils/utility.utils.ts
> Fix SQL Queries

- Clients/src/presentation/assets/icons/chevron-down-grey.svg
- Clients/src/presentation/assets/icons/chevron-down-white.svg
- Clients/src/presentation/components/Inputs/Dropdowns/ProjectFilter/ProjectFilterDropdown.tsx
- Clients/src/presentation/components/Inputs/Select/Multi/index.tsx
- Clients/src/presentation/components/Inputs/Select/ReviewerSelect/index.tsx
- Clients/src/presentation/components/Inputs/Select/index.css
- Clients/src/presentation/components/Inputs/Select/index.tsx
- Clients/src/presentation/components/StatusDropdown/index.tsx
- Clients/src/presentation/pages/Framework/index.tsx
- Replaced KeyboardArrowDownIcon from Material-UI with custom GreyDownArrowIcon SVG
- Updated import to use the new chevron-down-grey.svg icon
- Replaced KeyboardArrowDownIcon with custom WhiteDownArrowIcon SVG
- Used chevron-down-white.svg for the white variant
- Removed the CSS hover effect that rotated the icon 180 degrees on hover
- Fixed Arrow Rotation in Framework page:
Fixes #2047
> Ks 016 sep 16 figma icons 2047

- Clients/src/presentation/helpers/event-tracker-help.html
- Clients/src/presentation/helpers/organizational-frameworks-help.html
- Clients/src/presentation/helpers/settings-help.html
- Clients/src/presentation/helpers/task-management-help.html
- Clients/src/presentation/pages/Framework/index.tsx
- Clients/src/presentation/pages/SettingsPage/index.tsx
- Clients/src/presentation/pages/Tasks/index.tsx
- Clients/src/presentation/pages/WatchTower/index.tsx
- Tasks helper updated
- Event Tracker helper updated
- Settings helper updated
- Framework helper added
> Mo 220 sept 17 completing helpers

- Clients/src/presentation/pages/TrainingRegistar/index.tsx
- Clients/src/presentation/pages/TrainingRegistar/style.ts
Add status dropdown and search to training registry
Fixes #2144
> added-dropdown-status-and-search-for-training-registry-tab

- Clients/src/presentation/assets/icons/right-arrow-black.svg
- Clients/src/presentation/components/CreateProjectForm/index.tsx
- Clients/src/presentation/components/Forms/ProjectForm/index.tsx
- Clients/src/presentation/components/Modals/CreateTask/index.tsx
- Clients/src/presentation/components/Modals/NewModelInventory/index.tsx
- Clients/src/presentation/components/Modals/NewModelRisk/index.tsx
- Clients/src/presentation/pages/ComplianceTracker/1.0ComplianceTracker/ControlCategory.tsx
- Clients/src/presentation/pages/Framework/ISO27001/Annex/index.tsx
- Clients/src/presentation/pages/Framework/ISO27001/Clause/index.tsx
- Clients/src/presentation/pages/Framework/ISO42001/Annex/index.tsx
- Clients/src/presentation/pages/Framework/ISO42001/Clause/index.tsx
- Clients/src/presentation/pages/ISO/Annex/index.tsx
- Clients/src/presentation/pages/ISO/Clause/index.tsx
- Clients/src/presentation/pages/ISO/style.ts
- Clients/src/presentation/pages/ProjectView/ProjectSettings/index.tsx
Changed MUI icons to SVG icons for keyboardarrowdown, expandmore, save button. 
Fixes #2047
> Ks 020 sep 20 figma icons 2047

- Clients/src/presentation/pages/SettingsPage/index.tsx
Hide Slack from the Settings Page until all the integrations have been completed
> hide slack from settings page

- Servers/controllers/organization.ctrl.ts
- Servers/controllers/role.ctrl.ts
Added comprehensive JSDoc documentation for organization and role controllers.
**Changes:**
- Organization controller: Multi-tenant architecture, CRUD operations, tenant provisioning
- Role controller: RBAC system, role management operations
**Lines added:** ~395 lines of documentation
> docs: Add inline documentation for organization and role management

- Servers/domain.layer/models/organization/organization.model.ts
- Servers/domain.layer/models/role/role.model.ts
- Servers/domain.layer/models/user/user.model.ts
Added comprehensive JSDoc documentation for core data layer models.
**Changes:**
- User model: Schema, validation, password management, role authorization
- Organization model: Multi-tenancy, validation, factory methods
- Role model: RBAC system, standard role definitions
**Lines added:** ~365 lines of documentation
> docs: Add inline documentation for core data models

- Clients/src/presentation/pages/AITrustCenter/Subprocessors/index.tsx
Fixes in AI Trust Center
Fixes #2216
> fixes-in-ai-trust-center

- Clients/src/domain/interfaces/i.mitigation.ts
- Clients/src/domain/interfaces/iRiskForm.ts
Interfaces extracted from `Clients\src\presentation\components\AddNewRiskForm` directory:
- IMitigation added in domain layer
- IMitigationErrors added in domain layer
- IRiskFormValues added in domain layer
- IRiskFormErrors added in domain layer
- IMitigationSectionProps added in domain layer
- IRiskSectionProps added in domain layer
> Mo 233 oct 3 fe domain.lay details

- Clients/src/domain/interfaces/i.breadcrumbs.ts
- Clients/src/presentation/components/Breadcrumbs/PageBreadcrumbs.tsx
- Clients/src/presentation/components/Breadcrumbs/index.tsx
- Clients/src/presentation/components/Breadcrumbs/routeMapping.ts
- Clients/src/presentation/components/Sidebar/index.tsx
- Clients/src/presentation/pages/index.tsx
- Evidences -> Evidence
- IPageBreadcrumbsProps added
- IBreadcrumbItem added
- IBreadcrumbsProps added
- Fixing imports
Addressing to close #2291
> Mo 235 oct 4 domain.lay interfaces + Evidence

- Clients/src/application/hooks/useRegisterUser.tsx
- Clients/src/application/repository/user.repository.ts
- Clients/src/domain/types/User.ts
- Clients/src/presentation/components/Modals/NewModelRisk/index.tsx
- Clients/src/presentation/pages/Authentication/Login/index.tsx
- Clients/src/presentation/pages/SettingsPage/Team/index.tsx
- Fix TypeScript build errors in authentication and user management components
- Improve type safety with proper ApiResponse interface usage
- Resolve implicit any types and type casting issues
- **Login Component**: Fix token access pattern with proper type casting
- **Team Settings**: Convert string roleId to number, fix API response data access
- **NewModelRisk Modal**: Add explicit any[] typing for userData variable
- **User Repository**: Add proper ApiResponse<T> return types for all functions
- **User Registration Hook**: Fix User type conflicts with RegisterUser interface
- **User Types**: Add compatibility fields and ApiResponse interface
> fix: Improve TypeScript type safety across authentication and user management

- Clients/package-lock.json
- Clients/package.json
- Clients/src/presentation/components/Sidebar/index.tsx
Complete sidebar redesign with modern iconography, improved menu organization, and enhanced user experience.
- **Modern Icons**: Replaced all custom SVG icons with Lucide React icons (16px, 1.5px stroke)
- **Menu Restructuring**: Reorganized navigation into logical groups with top-level items
- **Visual Refinements**: Enhanced spacing, typography, and interaction states
- **Dependency**: Added `lucide-react@^0.544.0` for consistent icon system
```
Dashboard
Tasks
DISCOVERY
├── Project oriented view
├── Organizational view  
├── Vendors
└── Model Inventory
ASSURANCE
├── Risk Management
├── Bias & Fairness
├── Training Registry
├── Evidence
├── Reporting
└── AI Trust Center
GOVERNANCE
├── Policy Manager
└── Event Tracker
Settings
```
- Reduced menu item height to 32px for better density
- …
> feat: Redesign sidebar with 16px icons and menu grouping

- Clients/src/presentation/components/Table/EventsTable/index.tsx
Fixes console warning about TablePagination component being placed inside a Box wrapper.
The TablePagination component renders as a <td> element but was nested inside a <div> (Box), causing invalid HTML structure.
**Changes:**
- Replace Box wrapper with proper Table > TableBody > TableRow structure
- Move styling from Box to TablePagination component
- Eliminate console error when accessing Event Tracker page
> fix: Resolve DOM nesting error in EventsTable pagination

- Clients/src/domain/interfaces/i.button.ts
- Clients/src/domain/interfaces/i.chart.ts
- Clients/src/presentation/components/Button/CustomizableButton/index.tsx
- Clients/src/presentation/components/Button/FilterButton/index.tsx
- Clients/src/presentation/components/ButtonToggle/index.tsx
- Clients/src/presentation/components/Charts/StatusDonutChart.tsx
- Clients/src/presentation/pages/DashboardOverview/IntegratedDashboard.tsx
- Clients/src/presentation/utils/cardEnhancements.ts
- Clients/src/presentation/utils/statusColors.ts
- CustomizableButtonProps added in domain layer
- IFilterButtonProps replaced inside component
- IButtonToggleOption added in domain layer
- IButtonToggleProps added in domain layer
- IStatusData added
- IStatusDonutChartProps added
> Mo 236 oct 6 fixes enhancements
